#!/bin/sh

git remote update

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ] || [ $REMOTE = $BASE ]; then
    echo "Up-to-date"
else
    git pull && tsc && pm2 restart server
fi